name: Publish Python Package to PyPI and TestPYPI

on:
  workflow_dispatch


jobs:
 python-build-m-publish:
   name: Build and publish Python distribution 
   runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4   
  
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip

      - name: Build the wheel
        run: python -m build --wheel .
      - name: Publish to PyPI
        run: |
          python -m twine upload --repository pypi dist/*
          # Replace 'your_pypi_token' with your actual PyPI token
